# Generated by Django 4.2.7 on 2026-09-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_systemconfig_pdf_logo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='stock_policy',
            field=models.CharField(choices=[('allow', 'Permitir sin stock'), ('warn', 'Avisar y pedir confirmación'), ('block', 'Bloquear pedidos sin stock')], default='allow', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_override_stock',
            field=models.BooleanField(default=False, help_text='Con política "bloquear", puede confirmar pedidos sin stock suficiente'),
        ),
    ]
