# Generated by Django 4.2.7 on 2026-09-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_systemconfig_stock_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='cancelled_order_payments',
            field=models.CharField(choices=[('keep', 'Dejar los pagos como están'), ('review', 'Marcar para revisión'), ('refund', 'Reembolsar automáticamente')], default='keep', max_length=10),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='overpayment_policy',
            field=models.CharField(choices=[('allow', 'Permitir (queda saldo a favor)'), ('warn', 'Avisar y pedir confirmación'), ('block', 'Bloquear pagos mayores al saldo')], default='allow', max_length=10),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='payment_approval',
            field=models.CharField(choices=[('section', 'Cualquier usuario con escritura en Pagos'), ('restricted', 'Solo usuarios habilitados para aprobar pagos')], default='section', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_payments',
            field=models.BooleanField(default=False, help_text='Con aprobación restringida, puede aprobar, rechazar y reembolsar pagos'),
        ),
    ]
