# Generated by Django 4.2.7 on 2026-10-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_systemconfig_cancelled_order_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='favicon',
            field=models.TextField(blank=True),
        ),
    ]
