# Generated by Django 4.2.7 on 2026-10-02 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='audit_retention_days',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('section', models.CharField(blank=True, db_index=True, max_length=30)),
                ('action', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=300)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('success', models.BooleanField(db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
