# Generated by Django 4.2.7 on 2026-04-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=4, default=1.0, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lista de precios',
                'verbose_name_plural': 'Listas de precios',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='orders.pricelist'),
        ),
    ]
