# Generated by Django 4.2.7 on 2026-04-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='enabled_products',
            field=models.ManyToManyField(blank=True, related_name='enabled_for_customers', to='products.product'),
        ),
    ]
