# Generated by Django 4.2.7 on 2026-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_delivered_quantity_and_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Entrega parcial'), ('delivered', 'Entregado'), ('cancelled', 'Anulado')], default='pending', max_length=20),
        ),
    ]
