# Generated by Django 4.2.7 on 2026-09-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_customer_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de numeración',
                'verbose_name_plural': 'Secuencias de numeración',
            },
        ),
    ]
