# Generated by Django 4.2.7 on 2026-09-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Pago aprobado de un pedido anulado, pendiente de revisión'),
        ),
    ]
