# Generated by Django 4.2.7 on 2026-04-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_after',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_before',
            field=models.IntegerField(),
        ),
    ]
