# Generated by Django 4.2.7 on 2026-09-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Si está desactivado, los pedidos no validan stock disponible'),
        ),
    ]
