# Generated by Django 4.2.7 on 2026-10-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_track_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIntakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_item', to='products.product')),
            ],
            options={
                'verbose_name': 'Producto de la lista de ingreso',
                'verbose_name_plural': 'Lista de ingreso de stock',
                'ordering': ['position', 'id'],
            },
        ),
    ]
